### ISSUE TITLE
Secure problem

### ISSUE THREAD

**Issue by vetcher** [robbert229/jwt#12]
As described [here](https://www.reddit.com/r/golang/comments/2lu55c/restful_session_token/cly7mu6/), please change [your comparation](https://github.com/robbert229/jwt/blob/master/algorithms.go#L145) to default buildin [function](https://golang.org/pkg/crypto/hmac/#Equal) when hmac is used

With gratitude,
Vetcher

**Comment by robbert229** [comment]
Thanks! I am currently super busy and unable to update this myself. I am open to a PR though!

**Comment by robbert229** [comment]
Closed in #13
